spring:
  h2.console.enabled: on
  datasource.platform: h2
  jpa:
    show-sql: on
    properties.hibernate:
      format_sql: true
      use_sql_comments: true

logging.level.org.hibernate.type: trace

server:
  port: 8080
  error:
    include-exception: on
    include-stacktrace: never

